### ISSUE TITLE
Compile ZPL Project into .a Library for Easier Linux Integration

### ISSUE THREAD

**Issue by liusuchao** [zpl-c/zpl#117]
Hello
Creating this marvelous library has been an immense help in streamlining our application development. I'm extremely appreciative of your efforts.

I have an idea that our project could be compiled into a library that would be easier to use on linux.

**Comment by zpl-zak** [comment]
You can build zpl as a static library by writing a zpl.c file with the following content:
```c
#define ZPL_IMPL

// Set your distribution up to your likings
#define ZPL_NANO
#define ZPL_ENABLE_OPTS
#define ZPL_ENABLE_HASHING

// Include the library
#define ZPL_STATIC_LIB
#include <zpl.h>
```

and then compile it as a static library, you can then link against it as you would with any other library.

We do not plan to distribute static libraries ourselves due to the library's modular nature.

Hope this helps!
